language: python
python:
  - "3.6"
    
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  #- hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda create -q -n root-env python=$TRAVIS_PYTHON_VERSION
  - conda activate root-env
  - conda install root -c conda-forge
  - mkdir -p $HOME/awesome-workshop

cache:
  directories:
    - $HOME/awesome-workshop
    
stages:
  - skim_datasets
  - produce_histograms
  - make_plots
      
jobs:
  include:
    - stage: skim_datasets
      script:
        - mkdir -p $HOME/awesome-workshop/skims
        - bash skim.sh root://eospublic.cern.ch//eos/root-eos/HiggsTauTauReduced/ $HOME/awesome-workshop/skims
    - stage: produce_histograms
      script:
        - mkdir -p $HOME/awesome-workshop/histograms
        - bash histograms.sh $HOME/awesome-workshop/skims $HOME/awesome-workshop/histograms
    - stage: make_plots
      script:
        - mkdir -p $HOME/awesome-workshop/plots
        - bash plot.sh $HOME/awesome-workshop/histograms/histograms.root $HOME/awesome-workshop/plots
        - ls $HOME/awesome-workshop/plots


notifications:
  email:
    on_success: never
    on_failure: never
