language: ruby

services:
  - docker

before_install:
  - docker pull rootproject/root-conda:latest
  - docker run -ti rootproject/root-conda

script:
  #- bundle exec rake test
  - python --version
  - root-config --version
