language: python
python:
  - "3.6"
    
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  #- hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda create -q -n root-env python=$TRAVIS_PYTHON_VERSION
  - conda activate root-env
  - conda install root -c conda-forge
  - mkdir -p $HOME/awesome-workshop

cache:
  directories:
    - $HOME/awesome-workshop
    
stages:
  - skim_datasets
  - produce_histograms
  - make_plots
      
jobs:
  include:
    - stage: skim_datasets
      script:
        - mkdir -p $HOME/awesome-workshop/skims
        - bash skim.sh root://eospublic.cern.ch//eos/root-eos/HiggsTauTauReduced/ $HOME/awesome-workshop/skims
    - stage: produce_histograms
      script:
        - mkdir -p $HOME/awesome-workshop/histograms
        - bash histograms.sh $HOME/awesome-workshop/skims $HOME/awesome-workshop/histograms
    - stage: make_plots
      script:
        - mkdir -p $HOME/awesome-workshop/plots
        - bash plot.sh $HOME/awesome-workshop/histograms.root $HOME/awesome-workshop/plots
        - ls $HOME/awesome-workshop/plots
      addons:
        artifacts:
          debug: true
            paths:
              - $HOME/awesome-workshop/plots
            target_paths: $TRAVIS_BUILD_NUMBER
            #working_dir: WORKING_DIR
            #bucket: simplelance
            s3_region: us-west-1


#language: ruby

#services:
#  - docker

#before_install:
  #- docker pull rootproject/root-conda:latest
  #- docker run --rm -it rootproject/root-conda
  #- docker run -d --name=mydocker rootproject/root-conda
  #- docker ps -a

#script:
  #- docker exec -ti mydocker bash
  #- docker run --rm -it rootproject/root-conda
  #- python --version
  #- root-config --version
  #- exit

#before_install:
#- docker pull carlad/sinatra
#- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#- bundle exec rake test
