language: ruby

services:
  - docker

#before_install:
  #- docker pull rootproject/root-conda:latest
  #- docker run --rm -it rootproject/root-conda
  #- docker run -d --name=mydocker rootproject/root-conda
  #- docker ps -a

#script:
  #- docker exec -ti mydocker bash
  #- docker run --rm -it rootproject/root-conda
  #- python --version
  #- root-config --version
  #- exit

before_install:
- docker pull carlad/sinatra
- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
