language: ruby

services:
  - docker

before_install:
  - docker pull rootproject/root-conda:latest
  #- docker run --rm -it rootproject/root-conda
  #- docker run -d --name=mydocker rootproject/root-conda
  #- docker ps -a

script:
  #- docker exec -ti mydocker bash
  - docker run --rm -it rootproject/root-conda
  - python --version
  - root-config --version
  - exit
