language: python
python:
  # Conda doesn't actually use the Travis Python, but this keeps it organized.
  - "3.6"
before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n root-env python=$TRAVIS_PYTHON_VERSION
  - conda activate root-env
  - conda install root -c conda-forge

script:
  - python --version
  - root-config --version

#language: ruby

#services:
#  - docker

#before_install:
  #- docker pull rootproject/root-conda:latest
  #- docker run --rm -it rootproject/root-conda
  #- docker run -d --name=mydocker rootproject/root-conda
  #- docker ps -a

#script:
  #- docker exec -ti mydocker bash
  #- docker run --rm -it rootproject/root-conda
  #- python --version
  #- root-config --version
  #- exit

#before_install:
#- docker pull carlad/sinatra
#- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#- bundle exec rake test
