language: ruby

services:
  - docker

before_install:
  - docker pull rootproject/root-conda:latest
  - docker run -td rootproject/root-conda /bin/sh -c "bundle exec rake test"

script:
  - bundle exec rake test
  - python --version
  - root-config --version
